---
- name: Mac OS X will accept fish as a default shell
  lineinfile: dest=/etc/shells regexp=.*/fish$ line="/usr/local/bin/fish"
  sudo: true

- name: "change shell"
  command: chsh -s /usr/local/bin/fish {{ ansible_env.USER }}
  sudo: true

# Oh my fish
- stat: path={{ansible_user_dir}}/.local/share/omf
  register: omf

#- name: Install oh-my-fish framework
#  shell: fish <(curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install) && exit 0 executable=/bin/bash
#  when: omf.stat.isdir is not defined
