---
# neovim
- name: Install python neovim
  pip: name=neovim extra_args="--upgrade"

- name: Creates nvim folder
  file: path={{ansible_user_dir}}/.config/nvim/autoload state=directory mode=0755

# FVim Plug
- name: Install vim plug
  get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest={{ansible_user_dir}}/.config/nvim/autoload/plug.vim