---
# http://marcio.io/2015/07/supercharging-atom-editor-for-go-development/
# https://medium.com/@satya164/supercharged-javascript-development-in-atom-ea034e22eabc#.opzmo6qm7
atom_packages:
- seti-ui
- monokai-seti
- language-docker
- language-protobuf
- go-plus
- go-rename
#- file-icons
- dash
- highlight-line
#- gotags # gotags -tag-relative=true -R=true -sort=true -f="tags" -fields=+l .
- atom-beautify
- atom-ternjs
- auto-detect-indentation
- auto-update-packages
- autocomplete-modules
#- dockblockr
- editorconfig
- git-projects
- language-babel
- linter
- linter-eslint
- linter-htmlhint
- linter-csslint
- linter-flow
- nuclide-flow
- open-recent
- react
- sync-settings
- term3
- todo-show
- pigments
- tool-bar
- emmet
- autoprefixer
- vim-mode
- csscomb
- javascript-snippets
- csslint
- autocomplete-plus
- color-picker
- minimap
- git-plus
- remote-edit
- open-recent
- highlight-selected
- minimap-highlight-selected
- autoclose-html
- language-elm
- language-elixir
- autocomplete-elixir
