---
# dotfiles playbook

- name: "Clone dotfiles"
  git: repo=https://github.com/hasanozgan/dotfiles.git dest=/{{ansible_user_dir}}/.dotfiles recursive=yes 

- name: "Link files"
  file: src={{ansible_user_dir}}/.dotfiles/{{ item.path }} dest={{ansible_user_dir}}/{{ item.dest }} state=link
  with_items:
    - { path: "tmuxconf", dest: ".tmux.conf" }  
    - { path: "ctags",     dest: ".ctags" }
    - { path: "gitconfig", dest: ".gitconfig" }
    - { path: "bashrc",    dest: ".bashrc" }
    - { path: "config",    dest: ".config" }

#- name: "Install font"
#  file: src="{{ansible_user_dir}}/.dotfiles/fonts/Droid Sans Mono for Powerline.otf" dest="/{{ansible_user_dir}}/Library/Fonts/Droid Sans Mono for Powerline.otf" state=link

- name: "add shell"
  lineinfile: dest=/etc/shells line='/usr/local/bin/fish'
  sudo: true

- name: "change shell"
  command: chsh -s /usr/local/bin/fish {{ ansible_env.USER }}
  sudo: true
