---
# dotfiles playbook

# dotfiles
- name: "Clone dotfiles"
  git: repo=https://github.com/hasanozgan/dotfiles.git dest=/{{ansible_user_dir}}/.dotfiles recursive=yes 

- shell: chdir={{ansible_user_dir}}/.dotfiles make -f Makefile